# Git中向Github推送出错
当前新建了一个仓库branch-demo,并且成功关联了远程仓库remote-repo
但是此时本地仓库既不能向远程仓库推送数据，也不能获取远程的数据
![推送出错](vx_images/386165820272907.png =900x)
![拉取失败](vx_images/106050121244418.png =818x)
解决方案：
 * 执行 git pull --rebase origin master
 ![](vx_images/192800721252898.png =900x)
 * 解决冲突
 尝试推送不成功，但是发现出现rebase 2/4，说明存在问题
 ![尝试推送不成功](vx_images/583031021257937.png =900x)
提示冲突
![提示冲突](vx_images/364431421259232.png =900x)
找到冲突
![](vx_images/15631621260234.png "找到要解决的冲突" =900x)
解决冲突后，再此拉取rebase，提示是否继续
![](vx_images/170911821260411.png =900x)
提示冲突，继续解决，直到所有冲突解决完成
![](vx_images/230222021245963.png =900x)
当所有冲突已经解决，尝试拉取rebase
![](vx_images/178722321262242.png =900x)
可以拉取数据了！！
![](vx_images/172552721255287.png =900x)
